site_name: آموزش‌های غرفه‌داری

copyright: 'Copyright &copy; 2021 Mahdi Majidzadeh'

site_url: 'https://basalam-hub.ir'
site_author: 'Mahdi Majidzadeh'

repo_name: 'basalam-hub'
repo_url: 'https://github.com/MahdiMajidzadeh/basalam-hub'

lang: fa


theme:
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: 'material'
  palette:
    primary: teal
  highlightjs: true
  include_sidebar: false
  direction: 'rtl'
  language: 'fa'
  font: false
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.top

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css: 
  - 'extra/style.css'  

extra:
  search:
    language: 'en, fa'

nav:
  - شروع: 'index.md'
  - فروش گروهی: 'group-sell.md'